# Generated by Django 3.2.13 on 2022-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0002_rename_place_inmakesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmimg', models.ImageField(upload_to='pics')),
                ('tmname', models.CharField(max_length=250)),
                ('tmdesc', models.TextField()),
            ],
        ),
    ]
