# Generated by Django 3.2.13 on 2022-06-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tmdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tmimg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tmname',
            new_name='name',
        ),
    ]
